### PR TITLE
BUG: Fix markup selection with VTK9 updating tolerance

### LINKED ISSUE #5250: Markups cannot be picked after VTK9 upgrade
In some situations, markups fiducials cannot be picked (and their labels are not displayed). Sometimes changing the window size or changing zoom factor makes them pickable.

Setting opacity to 0.99 or changing to crosshair glyph fixes the issue, so it seems that the markups occlude themselves. vtkSelectVisiblePoints has a tolerance value, which should ensure that a glyph cannot cause the point detected as occluded, but maybe something has changed around that in VTK9. Maybe the real-world tolerance computation is impacted by changes in some automatic internal rescaling of coordinates (https://discourse.vtk.org/t/documentation-for-vertexmc-normalmc-mcdcmatrix-mvcmatrix/1883/3; history of vtkOpenGLPolyDataMapper.h contains a few more changes that might be related).

## Steps to reproduce

Type this into the Python console:

```python
import numpy as np
pts = np.array([
    [ 22.08201981, -23.33771133,  20.25755501],
    [ 22.24702835, -31.33755684,  21.34285164],
    [ 21.05020905, -33.57769394,  20.82586288],
    [ 19.80578232, -38.49482346,  21.96247864],
    [ 18.11996651, -39.62874985,  20.58876419],
    [ 15.6773119 , -43.51329041,  20.84062958],
    [ 14.88829422, -45.93460083,  22.75982285],
    [ 13.19761467, -49.92071915,  24.98643875],
    [ 11.26348495, -51.92196655,  24.92158699],
    ])

ptsNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")
slicer.util.updateMarkupsControlPointsFromArray(ptsNode, pts)
slicer.util.resetThreeDViews()  # to reset the box size
```

Point labels are not displayed and points cannot be clicked.

If opacity of the markups node is set to 0.99 or glyph type is set to crosshair then the points become pickable (and labels appear) again.

## Expected behavior

Markups points should be pickable if they are not occluded.

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

### PR DESCRIPTION
**Pull request by sankhesh**
(Edited by @jcfr)

Following the revamp of the z-buffer computation and coincident topology
resolution integrated in VTK9 (See [1][2]), the z-buffer values are
now different. This commit accounts for this change by increasing the
world tolerance associated with small spheroid objects (such as glyphs)
and by setting a tiny tolerance for normalized display coordinates.
These tolerances are used to configure vtkSelectVisiblePoints filter
used to determine visibility of markups used to enable/disable
selectability.

[1] update and improve the coincident rendering code
    https://github.com/Kitware/VTK/commit/3052137e6621684f9184b293b82c677e976c2f89

[2] Add support for camera based shift scale methods
https://github.com/Kitware/VTK/commit/8f3aef771a25b81d89ae591ef26aca5162c8c6b2

Fixes #5250

Co-authored-by: Andras Lasso <lasso@queensu.ca>

### CODE REVIEW

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx [hunk 1]
```diff
@@ -89,7 +89,7 @@ vtkSlicerMarkupsWidgetRepresentation3D::ControlPointsPipeline3D::ControlPointsPi
 
   this->SelectVisiblePoints = vtkSmartPointer<vtkSelectVisiblePoints>::New();
   this->SelectVisiblePoints->SetInputData(this->LabelControlPointsPolyData);
-  this->SelectVisiblePoints->SetTolerance(0.0); // we will set tolerance in world coordinate system
+  this->SelectVisiblePoints->SetTolerance(1e-4); // we will set tolerance in world coordinate system
```
Comment (jcfr) [inline Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: @lassoan  Look we will also need to update the comment.

Currently tolerance is set in world coordinate here:

https://github.com/Slicer/Slicer/blob/28bad9fd10e224c24d65853f1e0e92c3085a2582/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx#L905

https://github.com/Slicer/Slicer/blob/28bad9fd10e224c24d65853f1e0e92c3085a2582/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx#L1208

**Comment by jcfr** [comment]
I confirm this addressed the issue

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx (hunk 1 above)
Comment (sankhesh) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: @jcfr When looking into the issue, I found that the Z values were off by a minuscule difference and hence my change adds a tiny tolerance to offset floating point precision issues.

Comment (jcfr) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: @sankhesh should this be addressed in VTK proper as it seems to be a regression introduced by VTK9 ?  Or was VTK8 improperly working despite of us setting the tolerance to 0 ?

Comment (sankhesh) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: @jcfr It doesn't look like a VTK issue and hence fixed at the application level.

Comment (jcfr) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: Great. Thanks for the clarification

Comment (jcfr) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:92]: @lassoan  I would be curious to know what you think as you originally introduced https://github.com/Kitware/VTK/commit/c5ef1ee4ee3cb95dbd899a588c82c0a187a7566e

**Comment by lassoan** [comment]
I've tested this fix and it definitely improves the situation but it does not always work:

1. Sometimes labels randomly disappear for non-occluded control points (and the control point is not pickable anymore)

image

2. Sometimes labels for occluded control points appear and they are pickable (when they shouldn't)

image

Increasing the world tolerance from `this->ControlPointSize * 0.5` to `this->ControlPointSize * 0.5` in the two controlPoints->SelectVisiblePoints->SetToleranceWorld(...) method calls works much more robustly.

However, it seems that the z-buffer and coincident topology resolution has been completely changed in VTK9 and it introduces many other bugs, for example: https://github.com/Slicer/Slicer/issues/5316 and https://github.com/Slicer/Slicer/issues/5317.

Probably commits like these cause the regressions, as they seem to introduce an entirely different strategy how the z buffer is computed and used:
https://github.com/Kitware/VTK/commit/3052137e6621684f9184b293b82c677e976c2f89
https://github.com/Kitware/VTK/commit/a703742d254c9dbabe2d551761239decc435a434
https://github.com/Kitware/VTK/commit/8f3aef771a25b81d89ae591ef26aca5162c8c6b2

**Comment by sankhesh** [comment]
@lassoan Just so I understand clearly, why would points be occluded in the screenshot under bullet 2 in your comment above?

Can we reproduce this with a simple VTK example, somehow?

**Comment by jcfr** [comment]
> Just to confirm, did you test with https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407

@lassoan, could you check again ? 

Fixes (or updated version of these fixes) associated with both  [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407) and [MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413) have both been integrated on Nov 20 in  Slicer master (see https://github.com/Slicer/Slicer/commit/31c89f230919a953e56f6722718281ce6da49e06).

Also for convenience, I have rebased this topic on top of the current master.

Thanks :pray:

**Comment by jcfr** [comment]
I confirm  that for a given display coordinate the computed Z-value is now different between VTK8 and VTK9.

Question: 

### Context

* Slicer version from Nov 30 (https://github.com/Slicer/Slicer/commit/f5944be6417635670e5fd1e7ffcc92fc6e85195e)
* Two builds: `Slicer_VTK_VERSION_MAJOR` set to `8` or `9`

### Details

In an attempt to understand what changed between VTK8 and VTK9 regarding the z-buffer computation, we can use the following code:

```python
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutConventionalView)
slicer.util.mainWindow().size = qt.QSize(1135, 542)
slicer.util.setPythonConsoleVisible(True)

slicer.app.layoutManager().threeDWidget(0).threeDView().mrmlViewNode().SetBoxVisible(0)
slicer.app.layoutManager().threeDWidget(0).threeDView().mrmlViewNode().SetAxisLabelsVisible(0)

import numpy as np
pts = np.array([
    [ 15.6773119 , -43.51329041,  20.84062958],
    [ 14.88829422, -45.93460083,  22.75982285],
    ])

ptsNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")
slicer.util.updateMarkupsControlPointsFromArray(ptsNode, pts)
slicer.util.resetThreeDViews()  # to reset the box size

slicer.app.layoutManager().threeDWidget(0).threeDView().setZoomFactor(1)
slicer.app.layoutManager().threeDWidget(0).threeDView().zoomIn()


def displayZ(worldPoint, toleranceWorld):
  renderer = slicer.app.layoutManager().threeDWidget(0).threeDView().renderWindow().GetRenderers().GetFirstRenderer()
  directionOfProjection = renderer.GetActiveCamera().GetDirectionOfProjection()
  compositePerspectiveTransform = vtk.vtkMatrix4x4()
  compositePerspectiveTransform.DeepCopy(renderer.GetActiveCamera().GetCompositeProjectionTransformMatrix(renderer.GetTiledAspectRatio(), 0, 1))
  
  x = worldPoint
  xx = [x[0], x[1], x[2], 1.0]
  xx[0] -= directionOfProjection[0] * toleranceWorld
  xx[1] -= directionOfProjection[1] * toleranceWorld
  xx[2] -= directionOfProjection[2] * toleranceWorld
  view = [0., 0., 0., 0.]
  
  compositePerspectiveTransform.MultiplyPoint(xx, view)
  
  renderer.SetViewPoint(view[0]/view[3], view[1]/view[3], view[2]/view[3])
  renderer.ViewToDisplay()
  dx = renderer.GetDisplayPoint()
  
  z = renderer.GetZ(int(dx[0]), int(dx[1]))
  
  print("dx[2]: %s, z: %s" % (dx[2], z))


slicer.app.processEvents()
displayZ([15.6773119 , -43.51329041,  20.84062958], 0.131762)

slicer.app.processEvents()
displayZ([14.88829422, -45.93460083,  22.75982285], 0.131762)
```

It adds two markups and only of them can be selected when using VTK9.

| | VTK8 | VTK9 |
|---|-----|-----|
| screenshot| image | image |
| markup 1 z display coord | 0.34755357495082845 | idem |
| markup 1 z buffer | 0.7577236890792847 | 0.3539235293865204 |
| markup 1 selectable | :heavy_check_mark:  | :x:  |
| markup 2 z display coord | 0.726767 | idem |
| markup 2 z buffer | 0.8263306021690369 | 0.727088 |
| markup 2 selectable | :heavy_check_mark:  | :heavy_check_mark: |

--1
0.34755357495082845, z: 0.3539235293865204

--2
0.7223245254539085, z: 0.7270875573158264
0.726767, z 0.727088




To print the value of `ToleranceWorld`, the function [vtkSelectVisiblePoints::IsPointOccluded](https://github.com/Slicer/VTK/blob/slicer-v9.0.20201111-733234c785/Rendering/Core/vtkSelectVisiblePoints.cxx#L237) has been instrumented using the patches posted below.

* VTK9 patch:

```diff
diff --git a/Rendering/Core/vtkSelectVisiblePoints.cxx b/Rendering/Core/vtkSelectVisiblePoints.cxx
index 92e960f1a0..49e3cda3dc 100644
--- a/Rendering/Core/vtkSelectVisiblePoints.cxx
+++ b/Rendering/Core/vtkSelectVisiblePoints.cxx
@@ -236,6 +236,9 @@ float* vtkSelectVisiblePoints::Initialize(bool getZbuff)
 
 bool vtkSelectVisiblePoints::IsPointOccluded(const double x[3], const float* zPtr)
 {
+  std::cout << "----- IsPointOccluded -----" << std::endl;
+  std::cout << "this->ToleranceWorld " << this->ToleranceWorld << std::endl;
+  //this->Print(std::cout);
   double view[4];
   double dx[3], z;
   double xx[4] = { x[0], x[1], x[2], 1.0 };
@@ -246,19 +249,25 @@ bool vtkSelectVisiblePoints::IsPointOccluded(const double x[3], const float* zPt
     xx[2] -= this->DirectionOfProjection[2] * this->ToleranceWorld;
   }
 
+  std::cout << "xx[0] " << xx[0] << ", xx[1] " << xx[1] << ", xx[2] " << xx[2] << std::endl;
+
   this->CompositePerspectiveTransform->MultiplyPoint(xx, view);
   if (view[3] == 0.0)
   {
+    std::cout << "view[3] is 0.0" << std::endl;
     return false;
   }
   this->Renderer->SetViewPoint(view[0] / view[3], view[1] / view[3], view[2] / view[3]);
   this->Renderer->ViewToDisplay();
   this->Renderer->GetDisplayPoint(dx);
 
+  std::cout << "dx[0] " << dx[0] << ", dx[1] " << dx[1] << ", dx[2] " << dx[2] << std::endl;
+
   // check whether visible and in selection window
   if (dx[0] >= this->InternalSelection[0] && dx[0] <= this->InternalSelection[1] &&
     dx[1] >= this->InternalSelection[2] && dx[1] <= this->InternalSelection[3])
   {
+    std::cout << "zPtr " << zPtr << std::endl;
     if (zPtr != nullptr)
     {
       // Access the value from the captured zbuffer.  Note, we only
@@ -273,6 +282,8 @@ bool vtkSelectVisiblePoints::IsPointOccluded(const double x[3], const float* zPt
       z = this->Renderer->GetZ(static_cast<int>(dx[0]), static_cast<int>(dx[1]));
     }
 
+    std::cout << "dx[2] " << dx[2] << ", z " << z << ", Tolerance " << this->Tolerance << std::endl;
+
     if (dx[2] < (z + this->Tolerance))
     {
       return true;
```

* VTK8 patch:

```diff
diff --git a/Rendering/Core/vtkSelectVisiblePoints.cxx b/Rendering/Core/vtkSelectVisiblePoints.cxx
index f3616660e3..132224fca8 100644
--- a/Rendering/Core/vtkSelectVisiblePoints.cxx
+++ b/Rendering/Core/vtkSelectVisiblePoints.cxx
@@ -251,6 +251,9 @@ bool vtkSelectVisiblePoints::IsPointOccluded(
   const float *zPtr
   )
 {
+  std::cout << "----- IsPointOccluded -----" << std::endl;
+  std::cout << "this->ToleranceWorld " << this->ToleranceWorld << std::endl;
+  //this->Print(std::cout);
   double view[4];
   double dx[3], z;
   double xx[4] = {x[0], x[1], x[2], 1.0};
@@ -261,19 +264,25 @@ bool vtkSelectVisiblePoints::IsPointOccluded(
     xx[2] -= this->DirectionOfProjection[2] * this->ToleranceWorld;
   }
 
+  std::cout << "xx[0] " << xx[0] << ", xx[1] " << xx[1] << ", xx[2] " << xx[2] << std::endl;
+
   this->CompositePerspectiveTransform->MultiplyPoint(xx, view);
   if (view[3] == 0.0)
   {
+    std::cout << "view[3] is 0.0" << std::endl;
     return false;
   }
   this->Renderer->SetViewPoint(view[0]/view[3], view[1]/view[3], view[2]/view[3]);
   this->Renderer->ViewToDisplay();
   this->Renderer->GetDisplayPoint(dx);
 
+  std::cout << "dx[0] " << dx[0] << ", dx[1] " << dx[1] << ", dx[2] " << dx[2] << std::endl;
+
   // check whether visible and in selection window
   if ( dx[0] >= this->InternalSelection[0] && dx[0] <= this->InternalSelection[1] &&
     dx[1] >= this->InternalSelection[2] && dx[1] <= this->InternalSelection[3] )
   {
+    std::cout << "zPtr " << zPtr << std::endl;
     if (zPtr != nullptr)
     {
       // Access the value from the captured zbuffer.  Note, we only
@@ -289,6 +298,8 @@ bool vtkSelectVisiblePoints::IsPointOccluded(
         static_cast<int>(dx[1]));
     }
 
+    std::cout << "dx[2] " << dx[2] << ", z " << z << ", Tolerance " << this->Tolerance << std::endl;
+
     if (dx[2] < (z + this->Tolerance))
     {
       return true;
```
