### PR TITLE
BUG: Fix Capture toolbar in incorrect location at startup 

### LINKED ISSUE #8904: Qt6: Capture toolbar is large and appears incorrect location at startup with maximized window
## Summary

When Slicer is built with Qt6, on Windows, if Slicer window was maximized last time Slicer was used, at application startup the Capture toolbar appears large, out of place, and cannot be moved out of the way:

Image

Workaround:

```
captureToolbar=mainWindow().findChildren(qt.QToolBar)[-1]
mainWindow().addToolBar(qt.Qt.TopToolBarArea, captureToolbar)
```

## Steps to reproduce

- Maximize Slicer window
- Restart Slicer

## Environment
- Slicer version: Slicer-5.11.0 latest main
- Operating system: Windows 11

### PR DESCRIPTION
**Pull request by jamesobutler**
This closes #8904.

`BUG: Fix Capture toolbar in incorrect location at startup`
Similar to the qSlicerMarkupsModule and qSlicerSequencesModule, the toolbar action needs to be added to the right-click context menu and the main window state needs to be restored again once the module toolbar is available.

See the following existing code which this is based on:
https://github.com/Slicer/Slicer/blob/0d41c7f91bc8bc53aa1b74fb9ba0efbf730d16c2/Modules/Loadable/Sequences/qSlicerSequencesModule.cxx#L110-L132
https://github.com/Slicer/Slicer/blob/0d41c7f91bc8bc53aa1b74fb9ba0efbf730d16c2/Modules/Loadable/Markups/qSlicerMarkupsModule.cxx#L152-L172

### CODE REVIEW

File: Modules/Loadable/SceneViews/qSlicerSceneViewsModule.cxx [hunk 1]
```diff
@@ -34,7 +64,18 @@ qSlicerSceneViewsModule::qSlicerSceneViewsModule(QObject* _parent)
 }
 
 //-----------------------------------------------------------------------------
-qSlicerSceneViewsModule::~qSlicerSceneViewsModule() = default;
+qSlicerSceneViewsModule::~qSlicerSceneViewsModule()
+{
+  Q_D(qSlicerSceneViewsModule);
```
Comment (lassoan) [inline Modules/Loadable/SceneViews/qSlicerSceneViewsModule.cxx]: It is enough to have this capture toolbar deletion in qSlicerSceneViewsModulePrivate.

**Comment by lassoan** [comment]
@jamesobutler thanks a lot for working on fixing this - it was a really annoying issue!
