### PR TITLE
BUG: Fix MIP and MinIP VolumeRendering with SSAO render pass

### LINKED ISSUE #7560: MIP volume rendering MIP does not appear if shadows visibility is enabled
## Summary

Volume rendering MIP (minimum/maximum intensity projection) is incompatible with shadows option. The volume does not appear if "Shadows visibility" option is enabled in the 3D view.

## Environment
- Slicer version: Slicer-5.7.0 2024-01-25
- Operating system: all

### PR DESCRIPTION
**Pull request by Thibault-Pelletier**
SSAO pass is not compatible with MIP and MinIP Volume rendering blend modes.

When the SSAO pass is active and the volume has MIP or MinIP blend modes, the SSAO pass is removed from the actor's `vtkOpenGLRenderPass::RenderPasses()` information. key.

The `vtkOpenGLRenderPass::RenderPasses()` key is entirely removed if after SSAO pass removal the key is empty to avoid crashes in the GPU mapper.

Following this fix, some visual artifacts remain when displaying geometry inside the volume in MIP / MinIP due to improper SSAO texture cleanup. These artifacts can only be addressed in the VTK shader code.

Closes #7560

image

### CODE REVIEW

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 1]
```diff
@@ -141,6 +148,23 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
     }
     virtual ~Pipeline() = default;
 
+    static void RemoveSSAORenderPassIfNeeded(vtkObject* sender, unsigned long eid, void* clientData, void* callData)
+    {
+      auto client = static_cast<Pipeline*>(clientData);
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]:
```suggestion
      Pipeline* pipeline = reinterpret_cast<Pipeline*>(clientData);
```

Along with renaming `client` to `pipeline` below

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 2]
```diff
@@ -141,6 +148,23 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
     }
     virtual ~Pipeline() = default;
 
+    static void RemoveSSAORenderPassIfNeeded(vtkObject* sender, unsigned long eid, void* clientData, void* callData)
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: `RemoveSSAORenderPassIfNeeded` ->  `OnVolumeActorInformationModified` ?

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 3]
```diff
@@ -141,6 +148,23 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
...
+    {
+      auto client = static_cast<Pipeline*>(clientData);
+      if (!client || !client->DoRemoveSSAORenderPass)
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]:
```suggestion
      if (eid != vtkCommand::ModifiedEvent)
      {
        return;
      }
      if (!pipeline || !pipeline->DoRemoveSSAORenderPass)
```

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 4]
```diff
@@ -155,6 +179,12 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
     vtkSmartPointer<vtkImageStencil> StencilFilter;
     vtkSmartPointer<vtkImageGaussianSmooth> Gaussian;
     vtkSmartPointer<vtkImageMathematicsAddon> ImageMathematics;
+
+    /// Flag controlling if the volume actor SSAO pass should be removed.
+    /// As of VTK 9.5.1 SSAO pass is not compatible with blend modes not writing volume normals (MIP, MinIP)
+    mutable bool DoRemoveSSAORenderPass{ false };
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]:
```suggestion
    bool DoRemoveSSAORenderPass{ false };
```

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 5]
```diff
@@ -155,6 +179,12 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
     vtkSmartPointer<vtkImageStencil> StencilFilter;
     vtkSmartPointer<vtkImageGaussianSmooth> Gaussian;
     vtkSmartPointer<vtkImageMathematicsAddon> ImageMathematics;
+
+    /// Flag controlling if the volume actor SSAO pass should be removed.
+    /// As of VTK 9.5.1 SSAO pass is not compatible with blend modes not writing volume normals (MIP, MinIP)
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]:
```suggestion
    /// Whether to disable the SSAO render pass for this volume actor.
    /// As of VTK 9.5.1, SSAO requires per-fragment normals, which MIP and MinIP
    /// blend modes do not generate.
    /// See https://www.kitware.com/screen-space-ambient-occlusion-for-volumes/
```

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 6]
```diff
@@ -141,6 +148,23 @@ class vtkMRMLVolumeRenderingDisplayableManager::vtkInternal
...
+      {
+        return;
+      }
+
+      // SSAO pass adds in a vtkOpenGLRenderPass::RenderPasses() flag to the volume actor information in pre render pass.
+      // Removing this pass from the information will disable the SSAO pass for the volume while keeping SSAO for other
+      // objects in the renderer.
+      if (client->VolumeActorInformation->Has(vtkOpenGLRenderPass::RenderPasses()))
+      {
+        client->VolumeActorInformation->Remove(vtkOpenGLRenderPass::RenderPasses());
```
Comment (lassoan) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: Does this remove all render passes? Could that have side effects? Would it be possible to only remove the SSAO render pass?

Comment (jcfr) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: Also it looks like `RenderPasses()` is of type `vtkInformationObjectBaseVectorKey` and is probably intended to hold information for each passes ? I am then wondering if `vtkOpenGLRenderer::DeviceRenderOpaqueGeometry` should be updated to inspect `RenderPasses()` ...

Comment (Thibault-Pelletier) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: Very good remark. I'm checking with @LucasGandel how to optimize this.

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx (hunk 3 above)
Comment (Thibault-Pelletier) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: I have merged all checks in one if line

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx (hunk 6 above)
Comment (Thibault-Pelletier) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: I have just edited the code to only remove the SSAO pass which seems to be working.

Regarding artifacts, there is one visual artifact for the volume at the moment (with SSAO + MIP + segmentation displayed ).

Problem is linked to shader textures updates during the SSAO pass.
We are checking with @LucasGandel if there is a workaround possible in Slicer or if this would be a VTK fix.

image

Comment (Thibault-Pelletier) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: I have checked with @LucasGandel and this artefact cannot be solved from 3D Slicer but needs to be addressed in VTK. Lucas will open an issue for this sometimes next week.

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx [hunk 7]
```diff
@@ -75,6 +75,9 @@
 #include <vtkVolumeProperty.h>
 #include <vtkDoubleArray.h>
 #include <vtkVolumePicker.h>
+#include <vtkInformation.h>
+#include <vtkOpenGLRenderPass.h>
+#include <vtkSSAOPass.h>
```
Comment (jcfr) [inline Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: Nitpick: Despite of having the last include in the "wrong" location, can we try to include the new ones keeping the list sorted alphabetically ?

Comment (Thibault-Pelletier) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: I just sorted the VTK includes in this commit (let me know if that's ok)

**Comment by jcfr** [comment]
:pray: @Thibault-Pelletier and @LucasGandel for addressing this and identifying the next steps :100: 

Considering this is a net improvement, I suggest we move forward with integration :rocket: 

Before doing so, I suggest we do the following:
* Update this pull request description to more accurately describe the fix
* Update the commit message as the approach implemented has evolved.
* Open a new issue to track the fact there are remaining artifact 

@Thibault-Pelletier  Could you help with this ?

File: Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx (hunk 7 above)
Comment (jcfr) [reply Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx]: We usually focus on having the newly introduced headers sorted without "updating" the complete list. We prefer to keep this for bulk changes we can later exclude from the history by updating `.git-blame-ignore-revs`[^1].

That said, adding a first commit titled `STYLE: Sort include in vtkMRMLVolumeRenderingDisplayableManager` would also be a sensible.

[^1]: https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs

**Comment by Thibault-Pelletier** [comment]
@jcfr I have just updated the commit message and opened a new issue with remaining artifacts to be handled.

I have also split the commits in two with the include sort and updated commit (synced with this PR).

Let me know if there is something else to do.

**Comment by Thibault-Pelletier** [comment]
For information, there seems to be some leaks related to the SSAO.
It's unrelated to the BUG / FIX but I'm having a look and I may push a dedicated commit for that if I find the root of the issue.

**Comment by jcfr** [comment]
Thanks :pray: 

I will build the branch locally & approve when it completes :rocket:

**Review by jcfr — DISMISSED** [review]

**Comment by jcfr** [comment]
How about changing the commit message and PR title:

`BUG: Fix VolumeRendering with SSAO render pass` -> `BUG: Fix MIP and MinIP VolumeRendering with SSAO render pass`

Since we leverage the automatic change log generation (based on the PR title), being able to have more context from the title is useful.

**Comment by Thibault-Pelletier** [comment]
@jcfr I added a small cleanup for the SSAO resources. This doesn't fix the full leaks when MIP is activated / deactivated but I don't seem to find the root of the issue...

**Review by jcfr — APPROVED** [review]

**Comment by jamesobutler** [comment]
FYI, in my Slicer custom app I'm seeing vtkDebugLeaks due to `BUG: Fix MIP and MinIP VolumeRendering with SSAO render pass` which doesn't appear to be completely resolved by `BUG: Fix SSAO resource leaks`. I'm trying to determine a way to replicate with Slicer and may otherwise post an attempt to resolve.

image

**Comment by Thibault-Pelletier** [comment]
Yes. As I mentionned the fix was only partial for the leaks. I wasn't able to pin point where it could originate from and the overall test setup isn't very suited to fast exploration for this type of problem...
