### PR TITLE
BUG: Fix missing Markups ROI fill in some views

### LINKED ISSUE #7944: Markups ROI not shown with fill opacity for Coronal slice orientation
## Summary

As originally reported at https://discourse.slicer.org/t/roi-markup-is-not-filled-with-color-in-coronal-view-in-slicer-5-6-0/33341:

A Markups ROI object with a visible 2D fill opacity shows that there an issue with the display of that fill when the slice orientation is "Coronal". 

## Steps to reproduce
```python
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)
roi_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsROINode")
roi_node.SetSize([100, 100, 100])
```
image

## Environment
- Slicer version: Slicer-5.7.0-2024-09-17 (as of https://github.com/Slicer/Slicer/commit/114731d5f71167f1a2da81ed2494c8201d6a1654), Slicer 5.6.2, 5.4.0
- Operating system: Windows, an issue on Linux and likely on macOS as well

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Contour triangulation would occasionally fail in some views depending on view orientation.

This was due to a failure in vtkContourTriangulator. Adding vtkCleanPolyData before vtkContourTriangulator in the pipeline fixes the issues.

Fix #7944

### CODE REVIEW

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h [hunk 1]
```diff
@@ -94,6 +95,7 @@ class VTK_SLICER_MARKUPS_MODULE_VTKWIDGETS_EXPORT vtkSlicerROIRepresentation2D :
   vtkSmartPointer<vtkTransform>               ROIToWorldTransform;
   vtkSmartPointer<vtkTransformPolyDataFilter> ROIToWorldTransformFilter;
   vtkSmartPointer<vtkCutter>                  ROIOutlineCutter;
+  vtkSmartPointer<vtkCleanPolyData>            ROIOutlineCleaner;
```
Comment (jcfr) [inline Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h:98]:
```suggestion
  vtkSmartPointer<vtkCleanPolyData>           ROIOutlineCleaner;
```

**Review by jcfr — APPROVED** [review]
Locally tested, and I confirm that the original issue is fixed :pray:
