### PR TITLE
BUG: Fixed issue with adding new node after rename cancelation

### LINKED ISSUE #6002: Cancelling "Create new (node) as ..." dialog should not create new object
Cancelling "Create new _X_ as ..." dialogue creates new object with the default name (as if from "Create new _X_"), but clicking `Cancel` should not produce any object.  
I think this happens in several modules, with different types of object, including `Table` and `Volume`.  

## Steps to reproduce

Invoke "Create new Table as ..." dialogue, such as for the _Output table_ of the **Segment Statistics** module.
Click `Cancel`.
This creates a new Table object with a default name.  

## Expected behaviour

Should not create any new object.  

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10 x64

### PR DESCRIPTION
**Pull request by aramSofthenge**
Fixes #6002

Additional minor improvements

### CODE REVIEW

File: Libs/MRML/Widgets/qMRMLNodeComboBox.cxx [hunk 1]
```diff
@@ -695,16 +708,44 @@ void qMRMLNodeComboBox::renameCurrentNode()
...
+            this->setCurrentNode(newNode);
+            emit this->nodeAddedByUser(newNode);
+        }
+    }
+}
+
+// --------------------------------------------------------------------------
+QString qMRMLNodeComboBox::getNameFromDialog(const QString& dialogTitle, const QString& defaultName = QString(), bool* ok = nullptr)
+{
+  QString newName = QInputDialog::getText(this, dialogTitle, "New name:", QLineEdit::Normal, defaultName, ok);
```
Comment (pieper) [inline Libs/MRML/Widgets/qMRMLNodeComboBox.cxx:747]: Shouldn't "New name" be marked for translation?

File: Libs/MRML/Widgets/qMRMLNodeComboBox.cxx [hunk 2]
```diff
@@ -695,16 +708,44 @@ void qMRMLNodeComboBox::renameCurrentNode()
...
   }
-  node->SetName(newName.toUtf8());
-  emit currentNodeRenamed(newName);
+}
+// --------------------------------------------------------------------------
+void qMRMLNodeComboBox::createNodeAs(const QString& nodeTypeName)
+{
+    QString label = this->nodeTypeLabel(nodeTypeName);
+    bool okPressed = false;
+    QString dialogTitle = tr("Create New %1").arg(label);
```
Comment (pieper) [inline Libs/MRML/Widgets/qMRMLNodeComboBox.cxx:728]: Shouldn't this use the already translated `createNew` from above?  Or do you think having the argument might mean it translates to a different string in different languages.

File: Libs/MRML/Widgets/qMRMLNodeComboBox.cxx [hunk 3]
```diff
@@ -43,6 +43,15 @@
 #include <vtkMRMLNode.h>
 #include <vtkMRMLScene.h>
 
+// ----------------------------------------------------------------------------
+
+namespace
+{
+  const QString createNew = QObject::tr("Create new ");
+  const QString asSuffix = QObject::tr(" as...");
+  const QString renameTitlePrefix = QObject::tr("Rename ");
```
Comment (pieper) [inline Libs/MRML/Widgets/qMRMLNodeComboBox.cxx:52]: I don't know enough about all the languages possibly involved here, but it seems to me some languages may not structure the sentence the same way and these may not be easy to break down as prefix and suffix.

File: Libs/MRML/Widgets/qMRMLNodeComboBox.cxx [hunk 4]
```diff
@@ -695,16 +708,44 @@ void qMRMLNodeComboBox::renameCurrentNode()
...
+    if (okPressed && !nodeName.isEmpty())
+    {
+        vtkMRMLNode* newNode = this->addNode(nodeTypeName);
+        if (newNode != nullptr)
+        {
+            newNode->SetName(nodeName.toUtf8());
+            this->setCurrentNode(newNode);
+            emit this->nodeAddedByUser(newNode);
+        }
+    }
```
Comment (pieper) [inline Libs/MRML/Widgets/qMRMLNodeComboBox.cxx:741]: It seems like this is the key change to fix the reported issue.  Maybe it should be a dedicated commit and the i18n changes would be independent.

Or if the i18n changes at least make it better than it was before we could integrate these and then make further improvements in another PR.

**Review by pieper — CHANGES_REQUESTED** [review]
Thanks for working on this 👍

File: Libs/MRML/Widgets/qMRMLNodeComboBox.cxx (hunk 4 above)
Comment (aramSofthenge) [reply Libs/MRML/Widgets/qMRMLNodeComboBox.cxx:741]: If you think this is essencial, can you please explain the point?
Because I don't see any specific reason of doing this, this will take me extra effort to separate the commits. I also followed the contribution guidelines and did not notice such a requirement to separate different changes.

**Review by pieper — APPROVED** [review]
