### PR TITLE
BUG: Fix interaction handle visibility when changing displayed slice

### LINKED ISSUE #6922: Plane handler visibility is not updated correctly on using slice slider
## Summary

Reproduced in Slicer-5.3.0-2023-04-01-linux-amd64.

When a plane interaction handler is displayed in 2D views for a markup plane, its visibility is not updated correctly when changing slice.

## Steps to reproduce

- Create a markup plane
- Enable the translate interaction option
- Change slice displayed using the slider
- The interaction handler visibility is one slice update off and is correctly update when mouse pass over it.

https://user-images.githubusercontent.com/26160797/229798545-03eb3818-74b1-49d7-a8c7-3e2414fecb2d.mp4

## Expected behavior

Interaction handler disappear when it is not on the slice displayed.

## Environment

- Slicer version: Slicer-5.3.0-2023-04-01-linux-amd64.
- Linux Ubuntu 20.04.1

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Fixes an issue where interaction handles were not updated correctly when scrolling through Slices in 2D viewers. Ensures that interaction handles are updated after all other components. The UpdateFromMRMLInternal method replaces the UpdateFromMRML method in all representation subclasses, and is called by UpdateFromMRML in the base class. UpdateFromMRML also updates the interaction pipeline after UpdateFromMRMLInternal has been called.

Also fixes an issue where the ROI box is not visible in slices that are parallel to and intersecting with one of the ROI faces.

Fixes #6922

Co-authored by: Mathieu Albi <albi@certis-therapeutics.com>

### CODE REVIEW

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx [hunk 1]
```diff
@@ -192,11 +191,13 @@ void vtkSlicerROIRepresentation2D::UpdateCubeSourceFromMRML(vtkMRMLMarkupsROINod
...
   double sideLengths[3] = { 0.0, 0.0, 0.0 };
   roiNode->GetSizeWorld(sideLengths);
-  cubeSource->SetXLength(sideLengths[0]);
-  cubeSource->SetYLength(sideLengths[1]);
-  cubeSource->SetZLength(sideLengths[2]);
-
-  this->ROIOutlineActor->SetVisibility(vtkMath::Norm(sideLengths) >= 1e-6);
+  // Add a small amount to each axis so that the ROI is still visible when the slice view is parallel to
+  // and intersecting with one of the faces.
+  double epsilon = 1e-5;
```
Comment (lassoan) [inline Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx:196]: 1e-5 might not be small enough if the slice spacing is very small (e.g., someone loads a microscopy image and keep the length unit in mm). Could we use some spacing values from the slice node instead of an absolute distance value?

**Review by lassoan — COMMENTED** [review]
Thank you, it looks good, just added a few comments inline.

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx [hunk 2]
```diff
@@ -209,9 +209,9 @@ void vtkSlicerAngleRepresentation2D::BuildArc()
 }
 
 //----------------------------------------------------------------------
-void vtkSlicerAngleRepresentation2D::UpdateFromMRML(vtkMRMLNode* caller, unsigned long event, void *callData /*=nullptr*/)
+void vtkSlicerAngleRepresentation2D::UpdateFromMRMLInternal(vtkMRMLNode* caller, unsigned long event, void *callData /*=nullptr*/)
 {
-  Superclass::UpdateFromMRML(caller, event, callData);
```
[the remark this answers is not in the document]
Comment (Sunderlandkyl) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx:214]: I don't think so. Overriding UpdateFromMRML should still have the same effect as before.
Switching to UpdateFromMRMLInternal would just make the order of operations explicit (UpdateFromMRMLInternal first, then update interaction handles).

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx (hunk 1 above)
Comment (Sunderlandkyl) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx]: Ok, I've made the distance relative to the slice spacing.

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx [hunk 3]
```diff
@@ -190,13 +189,21 @@ void vtkSlicerROIRepresentation2D::UpdateCubeSourceFromMRML(vtkMRMLMarkupsROINod
     this->SetROISource(cubeSource);
     }
 
+  // Add a small amount to each axis so that the ROI is still visible when the slice view is parallel to
+  // and intersecting with one of the faces.
+  double sliceNormal_XY[4] = { 0.0, 0.0, 1.0, 0.0 };
+  double sliceNormal_World[4] = { 0, 0, 1, 0 };
+  vtkMatrix4x4* xyToRAS = this->GetSliceNode()->GetXYToRAS();
```
Comment (lassoan) [inline Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx:196]: Usually we get the slice spacing from `this->SliceLogic->GetLowestVolumeSliceSpacing()[2]`. I'm wondering if we should use that here.

Comment (Sunderlandkyl) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx]: Sure, done.

File: Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx [hunk 4]
```diff
@@ -190,13 +190,18 @@ void vtkSlicerROIRepresentation2D::UpdateCubeSourceFromMRML(vtkMRMLMarkupsROINod
     this->SetROISource(cubeSource);
     }
 
+  // Add a small amount to each axis so that the ROI is still visible when the slice view is parallel to
+  // and intersecting with one of the faces.
+  vtkMRMLSliceLogic* sliceLogic = this->GetApplicationLogic()->GetSliceLogic(this->GetSliceNode());
```
Comment (lassoan) [inline Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx:195]: These objects should be of course all valid, but just in case, who knows, it would be nice to add null-pointer checks (and we can use a default 1e-6 if we fail to get the actual thickness)

Comment (Sunderlandkyl) [reply Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx]: Done.

**Review by lassoan — APPROVED** [review]
This all looks good now. Thanks for your patience with all my nitpicky comments.
