### PR TITLE
BUG: Prevent segment editor error messages on scene close

### LINKED ISSUE #4662: Various traceback errors when closing scene after using Segment Editor
_This issue was created automatically from an original [Mantis Issue](https://mantisarchive.slicer.org/view.php?id=4662). Further discussion may take place here._

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
- Modified events are now blocked during parameter node initialization
- Error message is not displayed if no parameter node is found during updateWidgetFromMRML
- More thorough error checking for parameter and segmentation nodes in autocomplete effect

fixes #4662, #4664

### CODE REVIEW

File: Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx [hunk 1]
```diff
@@ -1166,11 +1166,10 @@ void qMRMLSegmentEditorWidget::updateWidgetFromMRML()
 
   if (!d->ParameterSetNode)
     {
-    qCritical() << Q_FUNC_INFO << ": Invalid segment editor parameter set node";
```
Comment (Sunderlandkyl) [inline Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx]: @lassoan This is to fix the from the steps in https://mantisarchive.slicer.org/view.php?id=4664.
The other solution would be to check if the parameter node exists before calling updateWidgetFromMRML from setMRMLScene.

Comment (lassoan) [reply Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx]: I agree that it makes sense to remove the error message here but before returning we should probably disable the widgets that we would normally update with valid content in this method.
