### PR TITLE
BUG: Fix crash when adding %s specifier to color legend label

### LINKED ISSUE #3802: Extend label format error checking in vtkSlicerScalarBarActor
_This issue was created automatically from an original [Mantis Issue](https://mantisarchive.slicer.org/view.php?id=3802). Further discussion may take place here._

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
If a string specifier followed by a float specifier were added to the label format string, the SNPRINTF call would crash when interpreting the double as a string pointer. Fixed by only printing the value to the first specifier, and by validating that the specifier defines a floating point type.

Fix #3802

### CODE REVIEW

File: Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.cxx [hunk 1]
```diff
@@ -422,3 +425,23 @@ void vtkSlicerScalarBarActor::ConfigureTitle()
...
+bool vtkSlicerScalarBarActor::ValidateFormatString(std::string& validatedFormat, std::string& prefix, std::string& suffix,
+  const std::string& requestedFormat, const std::string& typeString)
+{
+  // This regex finds sprintf specifications. Only the first is used to format the value
+  // Regex from: https://stackoverflow.com/a/8915445
+  std::string regexString = "%([0-9]\\$)?[+-]?([ 0]|'.{1})?-?[0-9]*(\\.[0-9]+)?[" + typeString + "]";
+  vtksys::RegularExpression specifierRegex = vtksys::RegularExpression(regexString);
+  vtksys::RegularExpressionMatch specifierMatch;
+  if (!specifierRegex.find(requestedFormat.c_str(), specifierMatch))
+  {
```
Comment (lassoan) [inline Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.cxx:439]: indentation

**Review by lassoan — DISMISSED** [review]
Thank you, it looks good to me. I've just found a small indentation issue, only fix it if it's easy for you.

File: Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.cxx (hunk 1 above)
Comment (Sunderlandkyl) [reply Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.cxx]: Thanks, fixed!

**Review by lassoan — APPROVED** [review]
Thank you!
