### PR TITLE
BUG: Fix missing toggle markups action in Markups Place button menu

### LINKED ISSUE #6830: Toggle markups toolbar option is not visible
## Summary

"Toggle markups toolbar" option is not visible in the dropdown menu of the place mode button in the mouse mode toolbar.

@jamesobutler could you check? It might be related to https://github.com/Slicer/Slicer/commit/32675b18cb60123a7a873889f8c7383549e3ad27

## Steps to reproduce

- Click Toggle markups toolbar to show the toolbar
- Create a new point list, drop a point in a view
-> ERROR: Cannot show/hide the markups toolbar by clicking on the down-arrow button of the place mode button ("Toggle markups toolbar" option is not visible)

This error is displayed in the Python console: `[Qt] QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'PlaceWidgetMenuWindow'`

## Expected behavior

When placing points, clicking the down-arrow button of the place mode button should show "Toggle markups toolbar" action in the dropdown menu.

## Environment
- Slicer version: Slicer-5.3.0-2023-02-10
- Operating system: Windows

### PR DESCRIPTION
**Pull request by jamesobutler**
This closes #6830.

This fixes the following error which was introduced by https://github.com/Slicer/Slicer/commit/32675b18cb60123a7a873889f8c7383549e3ad27: [Qt] QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'PlaceWidgetMenuWindow'

History about the changes that were previously made and the reasoning about the changes made here: https://github.com/Slicer/Slicer/issues/6830#issuecomment-1432061086

### CODE REVIEW

File: Base/QTGUI/qSlicerMouseModeToolBar.cxx [hunk 1]
```diff
@@ -172,6 +172,17 @@ void qSlicerMouseModeToolBarPrivate::init()
   q->addAction(this->PlaceWidgetAction);
 
   q->addAction(this->ToolBarAction);  // add Toggle Markups ToolBar action last
+
+  this->PlaceWidgetToolBarAction = new QAction(this);
```
Comment (jcfr) [inline Base/QTGUI/qSlicerMouseModeToolBar.cxx:176]: Could you add a comment here and also above `this->PlaceWidgetAction = new QAction(this);` to explain where each action is being used  ?

Comment (jamesobutler) [reply Base/QTGUI/qSlicerMouseModeToolBar.cxx:176]: `PlaceWidgetToolBarAction` is in the menu of the Place widget and that `ToolBarAction` is an action represented by a QToolButton in the Markups Toolbar?

Is that level of description clear for you? If so I'll add those comments.

Comment (jamesobutler) [reply Base/QTGUI/qSlicerMouseModeToolBar.cxx:176]: @jcfr Those docstrings have now been added.

**Comment by jcfr** [comment]
> re: force pushed `main` branch from f183acc to 4ce0d3c

This was an exceptional measure, for rational see https://github.com/Slicer/Slicer/issues/6860 and https://github.com/Slicer/Slicer/issues/6861

**Review by jcfr — APPROVED** [review]
