### PR TITLE
BUG: Fix Segmentation test failing on Linux due with long scalar type

### LINKED ISSUE #5427: Fix py_nomainwindow_SegmentationsModuleTest2 on Linux
This test is failing on Linux with either VTK8 or VTK9

(Incidentally, it is also failing on macOS because of path to long in shared library. See [here](http://slicer.cdash.org/test/16388347)) 

## Steps to reproduce

```
ctest -R py_nomainwindow_SegmentationsModuleTest2 -V 
[...]
test 407
    Start 407: py_nomainwindow_SegmentationsModuleTest2

407: Test command: /path/to/Slicer-VTK8-rwdi/Slicer-build/Slicer "--no-splash" "--testing" "--disable-cli-modules" "--no-main-window" "--additional-module-paths" "/path/to/Slicer-VTK8-rwdi/Slicer-build/lib/Slicer-4.13/qt-loadable-modules" "/path/to/Slicer-VTK8-rwdi/Slicer-build/lib/Slicer-4.13/qt-scripted-modules" "--additional-module-paths" "/path/to/Slicer-VTK8-rwdi/Slicer-build/lib/Slicer-4.13/qt-scripted-modules" "/path/to/Slicer-VTK8-rwdi/Slicer-build/lib/Slicer-4.13/cli-modules" "/path/to/Slicer-VTK8-rwdi/Slicer-build/lib/Slicer-4.13/qt-loadable-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/path/to/Slicer-VTK8-rwdi/Slicer-build/Modules/Loadable/Segmentations/Testing/Python', '/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python'], 'SegmentationsModuleTest2')"
407: Test timeout computed to be: 1500
407: When loading module  "CropVolume" , the dependency "ResampleScalarVectorDWIVolume" failed to be loaded.
407: qSlicerSequencesModulePrivate::addToolBar: no main window is available, toolbar is not added
407: -------------------------------------------
407: path: ['/path/to/Slicer-VTK8-rwdi/Slicer-build/Modules/Loadable/Segmentations/Testing/Python', '/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python']
407: testname: SegmentationsModuleTest2
407: -------------------------------------------
407: runTest (slicer.ScriptedLoadableModule.ScriptedLoadableModuleTest) ... No test is defined in ScriptedLoadableModuleTest
407: ok
407: Requested file has been found and checksum is OK: /tmp/Slicer-tmp-jcfr/SegmentationsModuleTest/TinyPatient_Seg.zip
407: Unzipping /tmp/Slicer-tmp-jcfr/SegmentationsModuleTest/TinyPatient_Seg.zip into /tmp/Slicer-tmp-jcfr/SegmentationsModuleTest successful
407: Loaded volume from file: /tmp/Slicer-tmp-jcfr/SegmentationsModuleTest/TinyPatient_Seg/TinyPatient_CT.nrrd. Dimensions: 10x10x10. Number of components: 1. Pixel type: int.
407: 
407: 
407: "Volume" Reader has successfully read the file "/tmp/Slicer-tmp-jcfr/SegmentationsModuleTest/TinyPatient_Seg/TinyPatient_CT.nrrd" "[0.02s]"
407: Multiple layer editing successful
407: 5 islands created (2 ignored)
407: 3 islands created (4 ignored)
407: 5 islands created (2 ignored)
407: Running test on margin effect
407: Testing shared labelmaps
407: Running margin effect with data type: 2, and overwriteMode 0
407: Running margin effect with data type: 2, and overwriteMode 2
407: Running margin effect with data type: 15, and overwriteMode 0
407: Running margin effect with data type: 15, and overwriteMode 2
407: Running margin effect with data type: 3, and overwriteMode 0
407: Running margin effect with data type: 3, and overwriteMode 2
407: Running margin effect with data type: 4, and overwriteMode 0
407: Running margin effect with data type: 4, and overwriteMode 2
407: Running margin effect with data type: 5, and overwriteMode 0
407: Running margin effect with data type: 5, and overwriteMode 2
407: Running margin effect with data type: 6, and overwriteMode 0
407: Running margin effect with data type: 6, and overwriteMode 2
407: Running margin effect with data type: 7, and overwriteMode 0
407: Running margin effect with data type: 7, and overwriteMode 2
407: Running margin effect with data type: 8, and overwriteMode 0
407: test_SegmentationsModuleTest2 (SegmentationsModuleTest2.SegmentationsModuleTest2) ... FAIL
407: 
407: ======================================================================
407: FAIL: test_SegmentationsModuleTest2 (SegmentationsModuleTest2.SegmentationsModuleTest2)
407: ----------------------------------------------------------------------
407: Traceback (most recent call last):
407:   File "/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py", line 44, in test_SegmentationsModuleTest2
407:     self.TestSection_MarginEffects()
407:   File "/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py", line 295, in TestSection_MarginEffects
407:     self.runMarginEffect(segment1, segment2, dataType, self.segmentEditorNode.OverwriteAllSegments)
407:   File "/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py", line 343, in runMarginEffect
407:     self.checkSegmentVoxelCount(1, 1)
407:   File "/path/to/Slicer/Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py", line 248, in checkSegmentVoxelCount
407:     self.assertEqual(imageStat.GetVoxelCount(), expectedVoxelCount)
407: AssertionError: 0 != 1
407: 
407: ----------------------------------------------------------------------
407: Ran 2 tests in 0.425s
407: 
407: FAILED (failures=1)
407: Traceback (most recent call last):
407:   File "<string>", line 1, in <module>
407:   File "/path/to/Slicer-VTK8-rwdi/Slicer-build/bin/Python/slicer/testing.py", line 26, in runUnitTest
407:     exitFailure()
407:   File "/path/to/Slicer-VTK8-rwdi/Slicer-build/bin/Python/slicer/testing.py", line 11, in exitFailure
407:     raise Exception(message)
407: Exception
407: vtkDebugLeaks has found no leaks.
1/1 Test #407: py_nomainwindow_SegmentationsModuleTest2 ...***Failed    3.67 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   3.71 sec

The following tests FAILED:
	407 - py_nomainwindow_SegmentationsModuleTest2 (Failed)
```

## Expected behavior

Passing test

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Due to limitations in casting VTK_LONG_MAX from double to long on Linux, it is not possible to erase from VTK_LONG segments in the Segment Editor. This issue comes up when trying to fill outside a segment with VTK_LONG_MAX using vtkImageThreshold (see https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Libs/vtkSegmentationCore/vtkSegmentationModifier.cxx#L370-L376).

Since VTK_LONG Segmentation are not likely to be used anyway, it makes sense to remove them rather than to find a workaround.

This commit removes VTK(_UNSIGNED)_LONG from SegmentationsModuleTest2, and removes the scalar type from vtkOrientedImageDataResample::CastImageForValue so that long type labelmaps won't be created.

Closes #5427

### CODE REVIEW

File: Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx [hunk 1]
```diff
@@ -1881,13 +1881,9 @@ void vtkOrientedImageDataResample::CastImageForValue(vtkOrientedImageData* image
...
       scalarType = VTK_DOUBLE;
       }
-    else if (value > VTK_LONG_MAX || value < VTK_LONG_MIN)
-      {
-      scalarType = VTK_FLOAT;
-      }
     else if (value > VTK_INT_MAX || value < VTK_INT_MIN)
       {
-      scalarType = VTK_LONG;
+      scalarType = VTK_FLOAT;
```
Comment (lassoan) [inline Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx:1886]: Can a `float` represent all `long int` values? If not then it may be better to use `double`.

File: Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py [hunk 2]
```diff
@@ -280,12 +280,8 @@ def TestSection_MarginEffects(self):
       vtk.VTK_UNSIGNED_SHORT,
       vtk.VTK_INT,
       vtk.VTK_UNSIGNED_INT,
-      vtk.VTK_LONG,
-      vtk.VTK_UNSIGNED_LONG,
       vtk.VTK_FLOAT,
       vtk.VTK_DOUBLE,
-      #vtk.VTK_LONG_LONG, # These types are unsupported in ITK
-      #vtk.VTK_UNSIGNED_LONG_LONG,
```
Comment (lassoan) [inline Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py:288]: If we remove types then we should leave a comment there explaining why.

**Review by lassoan — COMMENTED** [review]
Thank you! Added two comments.

**Comment by jcfr** [comment]
> re: This issue comes up when trying to fill outside a segment with VTK_LONG_MAX using vtkImageThreshold

Would it make sense to report an issue on https://gitlab.kitware.com/vtk/vtk/-/issues ?

**Comment by Sunderlandkyl** [comment]
@lassoan Comments should be addressed in 998ce4b.

**Review by lassoan — APPROVED** [review]
It looks good to me, thank you.
