### PR TITLE
BUG: Fix system git invocation in GSSAPI stub builds and generalize executable wrapper

### LINKED ISSUE #8612: https git endpoints not working with GitPython in current Preview
## Summary

Seems to be a kerberos / ssl version issue.

See: https://github.com/MorphoCloud/SlicerMorphoDepot/issues/47

## Steps to reproduce
```
import git
repo = git.Repo.clone_from("https://github.com/Slicer/Slicer", "/tmp/Slicer", branch="main")
```
This works on 5.8.1, but on the Preview build it results in this error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/repo/base.py", line 1541, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/repo/base.py", line 1412, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/util.py", line 504, in finalize_process
    proc.wait(**kwargs)
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
  cmdline: /usr/bin/git clone -v --branch=main -- https://github.com/Slicer/Slicer /tmp/Slicer
  stderr: 'Cloning into '/tmp/Slicer'...
/usr/lib/git-core/git-remote-https: symbol lookup error: /lib/x86_64-linux-gnu/libssh.so.4: undefined symbol: GSS_C_NT_USER_NAME, version gssapi_krb5_2_MIT
'
>>> repo = git.Repo.clone_from("http://github.com/Slicer/Slicer", "/tmp/Slicer", branch="main")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/repo/base.py", line 1541, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/repo/base.py", line 1412, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/util.py", line 504, in finalize_process
    proc.wait(**kwargs)
  File "/home/exouser/Downloads/Slicer-5.9.0-2025-07-25-linux-amd64/lib/Python/lib/python3.12/site-packages/git/cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
  cmdline: /usr/bin/git clone -v --branch=main -- http://github.com/Slicer/Slicer /tmp/Slicer
  stderr: 'Cloning into '/tmp/Slicer'...
/usr/lib/git-core/git-remote-http: symbol lookup error: /lib/x86_64-linux-gnu/libssh.so.4: undefined symbol: GSS_C_NT_USER_NAME, version gssapi_krb5_2_MIT
'
```

## Environment
- Slicer version: Slicer-5.9.0-2025-07-25
- Operating system: Linux - Ubuntu 24.04

### PR DESCRIPTION
**Pull request by jcfr**
This pull request addresses an issue where system tools such as `git` fail when invoked from within the Slicer launcher environment in builds using the GSSAPI stub (`Slicer_BUILD_KRB5_GSSAPI_STUB`). The injected stubbed `libgssapi_krb5.so.2` may cause runtime symbol resolution errors (e.g., `GSS_C_NT_USER_NAME` not found) in tools linked against `libssh`.

To resolve this:

* A new script, `exec-outside-slicer-env.sh`, has been introduced to **restore the original system environment** (via `APPLAUNCHER_0_` variables) before invoking a system binary.
* A `git` wrapper is installed into the Slicer `bin/` directory that uses this script to safely run the system `git` binary, enabling tools like GitPython to function correctly within the Slicer environment.

In addition:

* The wrapper infrastructure has been **generalized** by renaming the wrapper script template from `git.sh.in` to `system-executable-wrapper.sh.in`.
* Multiple wrappers can be installed via a loop, supporting future use cases beyond `git`.

Related issue and PR:

* Fixes #8612
* #8598

### CODE REVIEW

**Comment by jcfr** [comment]
While working on adding tests ... I realized that `git` itself doesn't link against `libgssapi_krb5` but tools like `ssh` and `git-remote-http` (as you pointed out in https://github.com/Slicer/Slicer/issues/8612#issuecomment-3137791304) are linked against it.

File: Utilities/Scripts/exec-outside-slicer-env.sh [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+
+  # Apply unset commands to clean current environment
+  for cmd in "${unset_commands[@]}"; do
+    eval "$cmd"
+  done
+
+  # Apply restore commands from saved environment
+  for cmd in "${restore_commands[@]}"; do
+    eval "$cmd"
+  done
```
Comment (jcfr) [inline Utilities/Scripts/exec-outside-slicer-env.sh:65]: This will be simplified once the AppLauncher is fixed to ensure calling `--launcher-load-environment` effectively override env variables:

```bash
eval(
  $slicer_executable \
    --launcher-load-environment 0 \
    --launcher-show-set-environment-commands)
```

This is not a stopper to move forward with review & integration :rocket:

**Review by pieper — APPROVED** [review]
Sweet 🚀
